// Templates name icons as "mdi-<name>"; add each new one to ICONS.
import { h } from 'vue'
import { aliases, mdi } from 'vuetify/iconsets/mdi-svg'
import {
  mdiAccount,
  mdiAlertDecagramOutline,
  mdiAlphaACircle,
  mdiAlphaCCircle,
  mdiAlphaSCircle,
  mdiAlphaTCircle,
  mdiArrowLeft,
  mdiArrowRight,
  mdiArrowRightCircle,
  mdiArrowUpBoldCircle,
  mdiBitbucket,
  mdiBookOpenVariant,
  mdiBug,
  mdiChat,
  mdiCheck,
  mdiCheckCircle,
  mdiCheckCircleOutline,
  mdiCloseCircle,
  mdiCog,
  mdiCompareHorizontal,
  mdiContentCopy,
  mdiDelete,
  mdiEye,
  mdiFileCode,
  mdiFileOutline,
  mdiFilterOutline,
  mdiGit,
  mdiGithub,
  mdiGitlab,
  mdiHeart,
  mdiHelpCircle,
  mdiHomeCity,
  mdiInformation,
  mdiInformationOutline,
  mdiKey,
  mdiKeyOutline,
  mdiLabel,
  mdiLabelMultiple,
  mdiLabelOutline,
  mdiLaptop,
  mdiLink,
  mdiLinkVariant,
  mdiListStatus,
  mdiLogout,
  mdiMinus,
  mdiMinusCircle,
  mdiMonitor,
  mdiOpenInNew,
  mdiPlus,
  mdiRefresh,
  mdiRocketLaunch,
  mdiScaleBalance,
  mdiSourceBranch,
  mdiSourceMerge,
  mdiSourcePull,
  mdiSwapHorizontal,
  mdiText,
  mdiThemeLightDark,
  mdiViewDashboard,
  mdiWeatherNight,
  mdiWeatherSunny,
  mdiWeb,
} from '@mdi/js'

const ICONS = {
  'mdi-account': mdiAccount,
  'mdi-alert-decagram-outline': mdiAlertDecagramOutline,
  'mdi-alpha-a-circle': mdiAlphaACircle,
  'mdi-alpha-c-circle': mdiAlphaCCircle,
  'mdi-alpha-s-circle': mdiAlphaSCircle,
  'mdi-alpha-t-circle': mdiAlphaTCircle,
  'mdi-arrow-left': mdiArrowLeft,
  'mdi-arrow-right': mdiArrowRight,
  'mdi-arrow-right-circle': mdiArrowRightCircle,
  'mdi-arrow-up-bold-circle': mdiArrowUpBoldCircle,
  'mdi-bitbucket': mdiBitbucket,
  'mdi-book-open-variant': mdiBookOpenVariant,
  'mdi-bug': mdiBug,
  'mdi-chat': mdiChat,
  'mdi-check': mdiCheck,
  'mdi-check-circle': mdiCheckCircle,
  'mdi-check-circle-outline': mdiCheckCircleOutline,
  'mdi-close-circle': mdiCloseCircle,
  'mdi-cog': mdiCog,
  'mdi-compare-horizontal': mdiCompareHorizontal,
  'mdi-content-copy': mdiContentCopy,
  'mdi-delete': mdiDelete,
  'mdi-eye': mdiEye,
  'mdi-file-code': mdiFileCode,
  'mdi-file-outline': mdiFileOutline,
  'mdi-filter-outline': mdiFilterOutline,
  'mdi-git': mdiGit,
  'mdi-github': mdiGithub,
  'mdi-gitlab': mdiGitlab,
  'mdi-heart': mdiHeart,
  'mdi-help-circle': mdiHelpCircle,
  'mdi-home-city': mdiHomeCity,
  'mdi-information': mdiInformation,
  'mdi-information-outline': mdiInformationOutline,
  'mdi-key': mdiKey,
  'mdi-key-outline': mdiKeyOutline,
  'mdi-label': mdiLabel,
  'mdi-label-multiple': mdiLabelMultiple,
  'mdi-label-outline': mdiLabelOutline,
  'mdi-laptop': mdiLaptop,
  'mdi-link': mdiLink,
  'mdi-link-variant': mdiLinkVariant,
  'mdi-list-status': mdiListStatus,
  'mdi-logout': mdiLogout,
  'mdi-minus': mdiMinus,
  'mdi-minus-circle': mdiMinusCircle,
  'mdi-monitor': mdiMonitor,
  'mdi-open-in-new': mdiOpenInNew,
  'mdi-plus': mdiPlus,
  'mdi-refresh': mdiRefresh,
  'mdi-rocket-launch': mdiRocketLaunch,
  'mdi-scale-balance': mdiScaleBalance,
  'mdi-source-branch': mdiSourceBranch,
  'mdi-source-merge': mdiSourceMerge,
  'mdi-source-pull': mdiSourcePull,
  'mdi-swap-horizontal': mdiSwapHorizontal,
  'mdi-text': mdiText,
  'mdi-theme-light-dark': mdiThemeLightDark,
  'mdi-view-dashboard': mdiViewDashboard,
  'mdi-weather-night': mdiWeatherNight,
  'mdi-weather-sunny': mdiWeatherSunny,
  'mdi-web': mdiWeb,
}

const mdiNamed = {
  component: (props) => {
    const path = ICONS[props.icon]

    if (import.meta.env.DEV && !path && String(props.icon).startsWith('mdi-')) {
      console.warn(`Icon "${props.icon}" is not registered in src/plugins/icons.js`)
    }

    return h(mdi.component, { ...props, icon: path || props.icon })
  },
}

export const icons = {
  defaultSet: 'mdi',
  aliases,
  sets: {
    mdi: mdiNamed,
  },
}
